version: '3.8'
services:
  api_db:
    image: postgres:latest
    networks:
      - mynetwork
    restart: always
    volumes:
      - db_api_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  api_backend:
    image: denisktv/api_profiles:latest
    networks:
      - mynetwork
    restart: always
    volumes:
      - static_api_value:/app/static/
      - media_api_value:/app/media/
    depends_on:
      - api_db
      - redis
    env_file:
      - ./.env

  api_nginx:
    image: nginx:latest
    restart: always
    networks:
      - mynetwork
    ports:
      - "83:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_api_value:/var/html/static/
      - media_api_value:/var/html/media/
    depends_on:
      - api_backend

  redis:
    image: redis:latest
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  celery:
    image: denisktv/celery:v1.0
    command: celery -A api_profiles worker --loglevel=info
    env_file:
      - .env
    networks:
      - mynetwork
    depends_on:
      - redis
      - api_db

networks:
  mynetwork:
    driver: bridge

volumes:
  static_api_value:
  media_api_value:
  db_api_value:
